UD_LIST = {
    'english': 'UD_English-EWT/en_ewt-ud-%s.conllu',
    'czech': 'UD_Czech-PDT/cs_pdt-ud-%s.conllu',
    'basque': 'UD_Basque-BDT/eu_bdt-ud-%s.conllu',
    'finnish': 'UD_Finnish-TDT/fi_tdt-ud-%s.conllu',
    'turkish': 'UD_Turkish-IMST/tr_imst-ud-%s.conllu',
    'tamil': 'UD_Tamil-TTB/ta_ttb-ud-%s.conllu',
    'korean': 'UD_Korean-Kaist/ko_kaist-ud-%s.conllu',
    'marathi': 'UD_Marathi-UFAL/mr_ufal-ud-%s.conllu',
    'urdu': 'UD_Urdu-UDTB/ur_udtb-ud-%s.conllu',
    'telugu': 'UD_Telugu-MTG/te_mtg-ud-%s.conllu',
    'indonesian': 'UD_Indonesian-GSD/id_gsd-ud-%s.conllu',

    # 'af': 'UD_Afrikaans-AfriBooms/af_afribooms-ud-%s.conllu',
    # 'be': 'UD_Belarusian-HSE/be_hse-ud-%s.conllu',
    # 'bg': 'UD_Bulgarian-BTB/bg_btb-ud-%s.conllu',
    # 'ca': 'UD_Catalan-AnCora/ca_ancora-ud-%s.conllu',
    # 'cu': 'UD_Old_Church_Slavonic-PROIEL/cu_proiel-ud-%s.conllu',
    # 'da': 'UD_Danish-DDT/da_ddt-ud-%s.conllu',
    # 'de1': 'UD_German-GSD/de_gsd-ud-%s.conllu',
    # 'de2': 'UD_German-HDT/de_hdt-ud-%s.conllu',
    # 'es1': 'UD_Spanish-GSD/es_gsd-ud-%s.conllu',
    # 'es2': 'UD_Spanish-AnCora/es_ancora-ud-%s.conllu',
    # 'et1': 'UD_Estonian-EDT/et_edt-ud-%s.conllu',
    # 'el': 'UD_Greek-GDT/el_gdt-ud-%s.conllu',
    # 'fa': 'UD_Persian-Seraji/fa_seraji-ud-%s.conllu',
    # 'fr1': 'UD_French-Sequoia/fr_sequoia-ud-%s.conllu',
    # 'fr2': 'UD_French-Spoken/fr_spoken-ud-%s.conllu',
    # 'fr3': 'UD_French-FTB/fr_ftb-ud-%s.conllu',
    # 'fr4': 'UD_French-GSD/fr_gsd-ud-%s.conllu',
    # 'fr5': 'UD_French-ParTUT/fr_partut-ud-%s.conllu',
    # 'ga': 'UD_Irish-IDT/ga_idt-ud-%s.conllu',
    # 'gd': 'UD_Scottish_Gaelic-ARCOSG/gd_arcosg-ud-%s.conllu',
    # 'gl1': 'UD_Galician-CTG/gl_ctg-ud-%s.conllu',
    # 'got': 'UD_Gothic-PROIEL/got_proiel-ud-%s.conllu',
    # 'he': 'UD_Hebrew-HTB/he_htb-ud-%s.conllu',
    # 'hi': 'UD_Hindi-HDTB/hi_hdtb-ud-%s.conllu',
    # 'hr': 'UD_Croatian-SET/hr_set-ud-%s.conllu',
    # 'hu': 'UD_Hungarian-Szeged/hu_szeged-ud-%s.conllu',
    # 'hy': 'UD_Armenian-ArmTDP/hy_armtdp-ud-%s.conllu',
    # 'la1': 'UD_Latin-ITTB/la_ittb-ud-%s.conllu',
    # 'la3': 'UD_Latin-PROIEL/la_proiel-ud-%s.conllu',
    # 'lt1': 'UD_Lithuanian-ALKSNIS/lt_alksnis-ud-%s.conllu',
    # 'lt2': 'UD_Lithuanian-HSE/lt_hse-ud-%s.conllu',
    # 'lv': 'UD_Latvian-LVTB/lv_lvtb-ud-%s.conllu',
    # 'lzh': 'UD_Classical_Chinese-Kyoto/lzh_kyoto-ud-%s.conllu',
    # 'mt': 'UD_Maltese-MUDT/mt_mudt-ud-%s.conllu',
    # 'it1': 'UD_Italian-ISDT/it_isdt-ud-%s.conllu',
    # 'it2': 'UD_Italian-ParTUT/it_partut-ud-%s.conllu',
    # 'it3': 'UD_Italian-PoSTWITA/it_postwita-ud-%s.conllu',
    # 'it4': 'UD_Italian-TWITTIRO/it_twittiro-ud-%s.conllu',
    # 'it5': 'UD_Italian-VIT/it_vit-ud-%s.conllu',
    # 'nl1': 'UD_Dutch-Alpino/nl_alpino-ud-%s.conllu',
    # 'nl2': 'UD_Dutch-LassySmall/nl_lassysmall-ud-%s.conllu',
    # 'no1': 'UD_Norwegian-Bokmaal/no_bokmaal-ud-%s.conllu',
    # 'no2': 'UD_Norwegian-NynorskLIA/no_nynorsklia-ud-%s.conllu',
    # 'no3': 'UD_Norwegian-Nynorsk/no_nynorsk-ud-%s.conllu',
    # 'orv': 'UD_Old_Russian-TOROT/orv_torot-ud-%s.conllu',
    # 'pl1': 'UD_Polish-LFG/pl_lfg-ud-%s.conllu',
    # 'pl2': 'UD_Polish-PDB/pl_pdb-ud-%s.conllu',
    # 'pt1': 'UD_Portuguese-Bosque/pt_bosque-ud-%s.conllu',
    # 'pt2': 'UD_Portuguese-GSD/pt_gsd-ud-%s.conllu',
    # 'qhe': 'UD_Hindi_English-HIENCS/qhe_hiencs-ud-%s.conllu',
    # 'ro1': 'UD_Romanian-Nonstandard/ro_nonstandard-ud-%s.conllu',
    # 'ro2': 'UD_Romanian-RRT/ro_rrt-ud-%s.conllu',
    # 'ru1': 'UD_Russian-GSD/ru_gsd-ud-%s.conllu',
    # 'ru2': 'UD_Russian-SynTagRus/ru_syntagrus-ud-%s.conllu',
    # 'ru3': 'UD_Russian-Taiga/ru_taiga-ud-%s.conllu',
    # 'sk': 'UD_Slovak-SNK/sk_snk-ud-%s.conllu',
    # 'sl1': 'UD_Slovenian-SSJ/sl_ssj-ud-%s.conllu',
    # 'sr': 'UD_Serbian-SET/sr_set-ud-%s.conllu',
    # 'sv1': 'UD_Swedish-LinES/sv_lines-ud-%s.conllu',
    # 'sv2': 'UD_Swedish-Talbanken/sv_talbanken-ud-%s.conllu',
    # 'swl': 'UD_Swedish_Sign_Language-SSLC/swl_sslc-ud-%s.conllu',
    # 'ug': 'UD_Uyghur-UDT/ug_udt-ud-%s.conllu',
    # 'uk': 'UD_Ukrainian-IU/uk_iu-ud-%s.conllu',
    # 'vi': 'UD_Vietnamese-VTB/vi_vtb-ud-%s.conllu',
    # 'wo': 'UD_Wolof-WTB/wo_wtb-ud-%s.conllu',
    # 'zh1': 'UD_Chinese-GSDSimp/zh_gsdsimp-ud-%s.conllu',
    # 'zh2': 'UD_Chinese-GSD/zh_gsd-ud-%s.conllu',
    # 'cop': 'UD_Coptic-Scriptorium/cop_scriptorium-ud-%s.conllu',
    # 'fro': 'UD_Old_French-SRCMF/fro_srcmf-ud-%s.conllu',
    # 'grc1': 'UD_Ancient_Greek-Perseus/grc_perseus-ud-%s.conllu',
    # 'grc2': 'UD_Ancient_Greek-PROIEL/grc_proiel-ud-%s.conllu',
}
